language: node_js
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJWCAXMKZ4EEHLUIQ
  secret_access_key:
    secure: kdY/NlxubqBeVtBH2O9pCzlbybcfvkRe7kmvCcicU5EtcimAvduhqjADZKgoTXEyDOiHt/MeOMqG2rmpjaK7+r5KlQbUNexsRVQgZQX1N3PcIY9nfFQCali0K0jlGnYL70L8Wmr9rFqon3N/cDIZc5j9Bgb70e8XDtxDurld7fzh3zqidExKx7YCJ7znyDdyxH3yI+71eE0Wb08GpHhUb0O6+kuV8gt/q8/h2nELbp6qPlLMq4y+I5cu7Xax+z+Xlivk9kt2R5JaYvYKUBAN4Dd2cLxiHVLdpvxYco8BBHD0rRFGrvBPxp8p9OwDOyY0BY/tcqTAEq7KUCNyDsWN65Qk1ferb9zveXdTXMk6ikqSw3lp6e97OCJdE9/bAYcaiAiFDTCWshGi29g+KEBnqJTVxCYhWUL9QPupNfdMBzIYV6oFaONmf1qOCqikBsujkE9n021G7gzm80sAdsVMqu6wowk5CD/yMaRp1RgRooVG/xWzLNXbbxOqb37cTsCRMxoGruc1Jr73q0LR7CwROePJ6QFhk/pS0sIW2zxL6N/Zkkduyz79X4JLNUQ6OzMJio7ZbWPhfhB8oaMLdBlWuCG21N/0/BLr9SVrDWWjr+CXQFjUwgwscShmgb1dBH6CQWfWY2zEBhUOJfdRlJzvCpuSOD0USySjX+CdObigbns=
  region: us-east-2
  app: poketMon
  env: poketmon-env
